# Generated by Django 4.2.21 on 2025-06-01 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(help_text="Type de l'expéditeur (manager, volunteer, coordinator)", max_length=50)),
                ('sender_id', models.CharField(help_text="ID réel de l'expéditeur", max_length=255)),
                ('receiver_type', models.CharField(blank=True, help_text='Type du destinataire', max_length=50, null=True)),
                ('receiver_id', models.CharField(blank=True, help_text='ID du destinataire si connu', max_length=255, null=True)),
                ('channel', models.CharField(help_text='Canal sur lequel le message a été publié', max_length=255)),
                ('request_id', models.CharField(help_text='ID de la requête', max_length=255)),
                ('message_type', models.CharField(help_text='Type du message (request, response)', max_length=50)),
                ('content', models.TextField(help_text='Contenu du message au format JSON')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure d'enregistrement du message")),
                ('is_processed', models.BooleanField(default=False, help_text='Indique si le message a été traité')),
            ],
            options={
                'verbose_name': 'Log de message',
                'verbose_name_plural': 'Logs de messages',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sender_id'], name='message_log_sender__33553f_idx'), models.Index(fields=['receiver_id'], name='message_log_receive_4fe6a9_idx'), models.Index(fields=['channel'], name='message_log_channel_2be0c4_idx'), models.Index(fields=['request_id'], name='message_log_request_0c48cf_idx'), models.Index(fields=['timestamp'], name='message_log_timesta_39fbcf_idx')],
            },
        ),
    ]
