# Generated by Django 5.2 on 2025-05-03 19:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_type', models.CharField(choices=[('manager', 'Workflow Manager'), ('volunteer', 'Volunteer Application')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('access_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['client_id'], name='communicati_client__fa8d84_idx'), models.Index(fields=['access_token'], name='communicati_access__cf3efc_idx')],
            },
        ),
    ]
